import { NextRequest, NextResponse } from 'next/server';
import { createAdminClient } from '@/lib/supabase/server';
import type { BookingStatus } from '@/types';

// GET /api/admin/bookings - List bookings with filters
export async function GET(request: NextRequest) {
  try {
    const supabase = await createAdminClient();
    const { searchParams } = new URL(request.url);

    const status = searchParams.get('status') as BookingStatus | null;
    const tourId = searchParams.get('tourId');
    const search = searchParams.get('search');
    const startDate = searchParams.get('startDate');
    const endDate = searchParams.get('endDate');
    const limit = parseInt(searchParams.get('limit') || '20');
    const offset = parseInt(searchParams.get('offset') || '0');

    let query = supabase
      .from('bookings')
      .select(`
        *,
        tour:tours (id, slug),
        booking_items (*)
      `, { count: 'exact' })
      .order('created_at', { ascending: false });

    if (status) {
      query = query.eq('status', status);
    }

    if (tourId) {
      query = query.eq('tour_id', tourId);
    }

    if (search) {
      query = query.or(
        `customer_name.ilike.%${search}%,customer_email.ilike.%${search}%,reference.ilike.%${search}%`
      );
    }

    if (startDate) {
      query = query.gte('booking_date', startDate);
    }

    if (endDate) {
      query = query.lte('booking_date', endDate);
    }

    query = query.range(offset, offset + limit - 1);

    const { data, error, count } = await query;

    if (error) {
      console.error('Error fetching bookings:', error);
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({
      bookings: data || [],
      total: count || 0,
      limit,
      offset,
    });
  } catch (error) {
    console.error('Error in GET /api/admin/bookings:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

// POST /api/admin/bookings - Create a new booking
export async function POST(request: NextRequest) {
  try {
    const supabase = await createAdminClient();
    const body = await request.json();

    const {
      tourId,
      bookingDate,
      customerName,
      customerEmail,
      customerPhone,
      customerNationality,
      status = 'confirmed',
      language = 'en',
      notes,
      items = [],
    } = body;

    // Validate required fields
    if (!tourId || !bookingDate || !customerName || !customerEmail) {
      return NextResponse.json(
        { error: 'Missing required fields: tourId, bookingDate, customerName, customerEmail' },
        { status: 400 }
      );
    }

    // Calculate totals from items
    let totalRetail = 0;
    let totalNet = 0;
    for (const item of items) {
      totalRetail += item.subtotal_retail || 0;
      totalNet += item.subtotal_net || 0;
    }

    // Generate voucher token
    // Note: booking reference will be auto-generated by database trigger (AST-237551, AST-237552, etc.)
    const voucherToken = `vt-${Date.now()}-${Math.random().toString(36).substring(2, 10)}`;

    // Create booking
    const { data: booking, error: bookingError } = await supabase
      .from('bookings')
      .insert({
        tour_id: tourId,
        booking_date: bookingDate,
        customer_name: customerName,
        customer_email: customerEmail,
        customer_phone: customerPhone || null,
        customer_nationality: customerNationality || null,
        total_retail: totalRetail,
        total_net: totalNet,
        currency: 'THB',
        status,
        language,
        voucher_token: voucherToken,
        notes: notes || null,
      })
      .select()
      .single();

    if (bookingError) {
      console.error('Error creating booking:', bookingError);
      return NextResponse.json({ error: bookingError.message }, { status: 500 });
    }

    // Create booking items
    if (items.length > 0) {
      const bookingItems = items.map((item: {
        item_type: string;
        item_id: string;
        item_name: string;
        quantity: number;
        retail_price_snapshot: number;
        net_price_snapshot: number;
        subtotal_retail: number;
        subtotal_net: number;
        metadata?: Record<string, unknown>;
      }) => ({
        booking_id: booking.id,
        item_type: item.item_type,
        item_id: item.item_id,
        item_name: item.item_name,
        quantity: item.quantity,
        retail_price_snapshot: item.retail_price_snapshot,
        net_price_snapshot: item.net_price_snapshot,
        subtotal_retail: item.subtotal_retail,
        subtotal_net: item.subtotal_net,
        metadata: item.metadata || null,
      }));

      const { error: itemsError } = await supabase
        .from('booking_items')
        .insert(bookingItems);

      if (itemsError) {
        console.error('Error creating booking items:', itemsError);
        // Booking was created, but items failed - return partial success
        return NextResponse.json({
          booking,
          warning: 'Booking created but some items failed to save',
        });
      }
    }

    // Fetch complete booking with items
    const { data: completeBooking } = await supabase
      .from('bookings')
      .select(`
        *,
        tour:tours (id, slug),
        booking_items (*)
      `)
      .eq('id', booking.id)
      .single();

    return NextResponse.json({ booking: completeBooking }, { status: 201 });
  } catch (error) {
    console.error('Error in POST /api/admin/bookings:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}


